services:
  - type: web
    name: social-media-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn social_media_api.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: social-media-db
          property: connectionString
databases:
  - name: social-media-db
    plan: free